### ISSUE TITLE
update to newer version

### ISSUE THREAD

**Issue by dkern** [bengro/angular-jquery-lazy#1]
Hello @bengro,

i saw your little plugin-plugin. :) Just a little hint, maybe update to a newer version of Lazy. You depends on Lazy 0.1.18, which could be a bit slow sometimes. The newer versions should be compatible as well without any changes. Maybe change your dependency description to `jquery-lazy >= 0.1.18`.

**Comment by bengro** [comment]
Thanks, I've updated my bower.json.
